#!/bin/bash

source $(dirname $0)/config.sh
TRACE_FILE=$1
OUTPUT_BASE=$2

pids=()
i=1
for host in "${EXPERIMENT_HOSTS[@]}"; do
    nohup ssh $host $SCRIPT_DIR/one-read-trace $i $TRACE_FILE ${OUTPUT_BASE}.$i &
    pids+=($!)
    i=$(( $i + 1 ))
done

for pid in "${pids[@]}"; do
    wait $pid
done
