#!/bin/bash

source $(dirname $0)/config.sh
TRACE_FILE=$1
OUTPUT_BASE=$2

pids=()
i=1
for host in "${EXPERIMENT_HOSTS[@]}"; do
    nohup ssh $host $SCRIPT_DIR/one-update-files $i ${EXPERIMENT_DIR}/update-files.log.${host} &
    echo $! > $EXPERIMENT_DIR/$host-update-files.pid
    i=$(( $i + 1 ))
done
