#!/bin/bash

set -e


source $(dirname $0)/config.sh
HADOOP_DIR=$(echo $EXPERIMENT_DIR/hadoop-*)
cd $HADOOP_DIR
which=$1
bin/hdfs dfs -mkdir hdfs://${HOST}:$HDFS_PORT/file/ || true
bin/hdfs dfs -mkdir hdfs://${HOST}:$HDFS_PORT/file/data/ || true
bin/hdfs dfs -copyFromLocal $GENERATED_FILES/file${which}* hdfs://${HOST}:$HDFS_PORT/file/data/
